### ISSUE TITLE
Incorrect warning: recommended version 2.2.10

### ISSUE THREAD

**Issue by AdamCoulterOz** [ebaauw/homebridge-soma#11]
Im getting a warning for my smart shades 2 firmware not being on 2.2.10, but they are already on the latest available according to the app (2.2.8)?

homebridge-soma v1.0.8
Homebridge v1.3.8

![image](https://user-images.githubusercontent.com/6822248/143669098-a75fb499-92ad-4fa3-bde5-f5ad8a8b6f64.jpeg)

![image](https://user-images.githubusercontent.com/6822248/143669122-59909b28-1b5d-44dc-becc-6f062a37d3c6.jpeg)

![image](https://user-images.githubusercontent.com/6822248/143669124-d9a21ee6-77d0-4903-a37f-39eefd9643ef.png)

**Comment by ebaauw** [comment]
That’s odd.  My Tilt 2 devices upgraded to v2.2.10 early October.  The [Firmware Updates](https://support.somasmarthome.com/hc/en-us/articles/360014397560-Firmware-Updates) page on the Soma help centre lists v2.2.9 as latest version (and doesn’t even mention v2.2.8).

I don’t have any Smart Shades myself, but I understand they use the same firmware.  I don’t know why the app doesn’t find new firmware to your devices.  I’m also puzzled that it shows “SOMA Smart Shades” without “2”.
Could you please list the output of `soma probe` of your devices?

**Comment by AdamCoulterOz** [comment]
I've just masked the mac address.

```sh
homebridge@raspberrypi:/var/lib/homebridge $ soma probe "Lounge Window"
soma probe: warning: xxxxxxxxxx: request 7: deviceInformation: discoverCharacteristic modelNumber: cannot discover characteristic
soma probe: warning: xxxxxxxxxx: request 7: deviceInformation: discoverCharacteristic modelNumber: cannot discover characteristic
soma probe: warning: xxxxxxxxxx: request 21: motorService: discoverCharacteristic motorSolarPanelVoltage: cannot discover characteristic
soma probe: warning: xxxxxxxxxx: request 21: motorService: discoverCharacteristic motorSolarPanelVoltage: cannot discover characteristic
soma probe: warning: xxxxxxxxxx: request 23: motorService: discoverCharacteristic motorSpeed: cannot discover characteristic
soma probe: warning: xxxxxxxxxx: request 23: motorService: discoverCharacteristic motorSpeed: cannot discover characteristic
```

```json
{
  "genericAccess": {
    "deviceName": "S",
    "appearance": "0x0000",
    "peripheralPreferredConnectionParameters": {
      "minimumConnectionInterval": 16,
      "maximumConnectionInterval": 32,
      "slaveLatency": 0,
      "connectionSupervisionTimeoutMultiplier": 80
    }
  },
  "genericAttribute": {},
  "deviceInformation": {
    "manufacturerName": "WazombiLabs",
    "serialNumber": "R-0103-kristjan-202108091359-4bcf29f-6.1",
    "hardwareRevision": "BLINDY_V9_6",
    "firmwareRevision": "f6d3ddd",
    "softwareRevision": "v2.2.8"
  },
  "batteryService": {
    "batteryLevel": 93
  },
  "timeService": {
    "localTime": "2021-11-27T20:37:13"
  },
  "motorService": {
    "motorCurrentState": {
      "position": 100,
      "triggers": []
    },
    "motorTargetState": 100,
    "motorTriggerRequest": {
      "command": "0x00",
      "id": 0
    },
    "motorTriggerResponse": {
      "status": "0x00",
      "command": "0x00"
    },
    "motorCalibration": {
      "venetianMode": false
    },
    "motorControl": "0x68",
    "motorNotify": false,
    "motorTouchButtonEnabled": false,
    "motorBatteryLevel": 415,
    "motorUnderVoltage": false
  },
  "shadeService": {
    "shadeControl": "0x00",
    "shadeName": "Lounge Window",
    "groupName": "",
    "shadeState": {
      "chargingLevel": 0,
      "panelLevel": 0
    },
    "shadeMacAddress": "XX-XX-XX-XX-XX-XX",
    "shadeConfig": {}
  }
}
```

**Comment by ebaauw** [comment]
Thanks, that's looking OK and very familiar.  
- The warnings are for whitelisted characteristics that the v2 devices don't carry - nothing to worry about.
- The `hardwareRevision`, "BLINDY_V9_6", indicates these are newer devices.  Three of my devices report "BLINDY_V9" and one "BLINDY_V9_3".  I understood from Soma that they were about to release new hardware, but I hadn't seen it before.
- The `serialNumber` value clearly isn't a serial number.  Instead, it seems to encode the firmware build time and number.   All my devices report "R-0103-kristjan-202109021819-4bcf29f-6.1".
- I don't know how the `firmwareRevision` relates to the `softwareRevision`, but all my devices report "7fe89db"
 and "v2.2.10".  This value is also reflected in the Soma Smart Shades app.

I would expect the SOMA Smart Shades app to offer to upgrade the firmware when checking.  I have no clue why it doens't.

Technically, the warnings are correct: I develop and test Homebridge SOMA against firmware v2.2.10.  I think I firmware-upgraded my devices to v2.2.9 when I got them, and started working on Homebridge SOMA against that version.  I haven't seen any changes between v2.2.9 and v2.2.10; if Homebridge SOMA works, I think it's safe to ignore these warnings.  They're issued only on Homebridge startup, and after a device reboots.

**Comment by AdamCoulterOz** [comment]
It's a warning that I can't do anything about? Seems like it shouldn't be there.

**Comment by Djelibeybi** [comment]
FYI, I just got 4 new SOMA Shades and all of them are stuck on 2.2.8 as well, while the two I had already upgraded to 2.2.10. Looks like SOMA must have pulled the firmware update.

**Comment by ebaauw** [comment]
No, the latest model has a different firmware version, see #15.  Handled in v1.0.11.
