### ISSUE TITLE
Add StatusLowBattery Characteristic

### ISSUE THREAD

**Issue by washcroft** [ebaauw/homebridge-soma#12]
Alongside BatteryLevel, can we add the StatusLowBattery characteristic so that there is a notification/indication when a Soma's battery level is getting too low? Maybe set when battery level is 10% or less? Thanks

**Comment by ebaauw** [comment]
It's a mandatory characteristic for the _Battery_ service, so it's already there, but, indeed, I don't set it yet.  Not sure how/weather the various HomeKit apps actually use this attribute: Eve gives me warnings when the _Battery Percentage_ drops below 20%, irrespective of _Status Low Battery_.

For Homebridge Hue, I currently use a config.json setting for the low battery threshold, but I don't like that approach.  For button cells you probably want to set the threshold to 80%, where for AA or AAA batteries 10% is more useful.  I find my SOMA Tilt 2 devices are still happy at 13% battery, so 10% seems reasonable for SOMA.  Short days this time of year in Amsterdam, and the solar panel doesn't capture enough light to keep the battery charged, especially on my North-West facing window.  I'll see if I can make a per-device threshold which can be set from HomeKit, but I'm not sure if Eve or Home+ will display custom characteristics on the _Battery_ service.

**Comment by washcroft** [comment]
Thank you. It may not be worth the trouble of having it customisable, since we know ~10% is about right for SOMA devices?

Here's how how the Home app shows a device reporting a low battery status. I'm fairly certain there is a notification too when it changes to low, I could be mistaken.

![image](https://user-images.githubusercontent.com/1866176/144482038-64477068-166e-4d15-b534-5d233af6f0aa.png)

**Comment by ebaauw** [comment]
In v1.0.9.
