### ISSUE TITLE
New SOMA hardware varient, warning may be inaccurate

### ISSUE THREAD

**Issue by brian4286** [ebaauw/homebridge-soma#15]
The warning may possibly need new logic. I just received new SOMA Smart Shades 2 that came with a new solar panel design. I noticed that the instructions did not quite match and I see this warning in the plugin:

`[SOMA] GR tall out: warning: recommended version: Smart Shades 2 v2.2.10`

The new SOMA Smart Shades 2's with the new solar panel apparently run a different firmware according to SOMA support. The current version is 2.2.8. What makes it confusing is the the change log for the firmware has not been updated to reflect this divergence in hardware nor if releases in the future will be pushed simultaneously for all hardware types.

**Comment by ebaauw** [comment]
Interesting.  Could you please log the output of `soma probe 'GR tall out'`.  Need to find out how to recognise the new hardware version.

**Comment by brian4286** [comment]
Here you go...

`{
  "genericAccess": {
    "deviceName": "S",
    "appearance": "0x0000",
    "peripheralPreferredConnectionParameters": {
      "minimumConnectionInterval": 16,
      "maximumConnectionInterval": 32,
      "slaveLatency": 0,
      "connectionSupervisionTimeoutMultiplier": 80
    }
  },
  "genericAttribute": {},
  "deviceInformation": {
    "manufacturerName": "WazombiLabs",
    "serialNumber": "R-0103-kristjan-202108091359-4bcf29f-6.1",
    "hardwareRevision": "BLINDY_V9_6",
    "firmwareRevision": "f6d3ddd",
    "softwareRevision": "v2.2.8"
  },
  "batteryService": {
    "batteryLevel": 89
  },
  "timeService": {
    "localTime": "2021-12-22T16:59:29"
  },
  "motorService": {
    "motorCurrentState": {
      "position": 100,
      "triggers": []
    },
    "motorTargetState": 100,
    "motorTriggerRequest": {
      "command": "0x00",
      "id": 0
    },
    "motorTriggerResponse": {
      "status": "0x00",
      "command": "0x00"
    },
    "motorCalibration": {
      "venetianMode": false
    },
    "motorControl": "0x01",
    "motorNotify": false,
    "motorTouchButtonEnabled": false,
    "motorBatteryLevel": 413,
    "motorUnderVoltage": false
  },
  "shadeService": {
    "shadeControl": "0x00",
    "shadeName": "GR tall out",
    "groupName": "",
    "shadeState": {
      "chargingLevel": 182,
      "panelLevel": 2
    },
    "shadeMacAddress": "DF-11-40-F5-QK-9A",
    "shadeConfig": {}
  }
}`

From SOMA support it appears this may be related to the solar panel and not necessary the motor. This is part of their response:

> The newest version for Smart Shades devices with the old solar panel is 2.2.10
> The newest version for Smart Shades devices with the new solar panel is 2.2.8

**Comment by ebaauw** [comment]
In v1.0.11.
