### ISSUE TITLE
Cannot update to latest version?

### ISSUE THREAD

**Issue by costispavlou** [ebaauw/homebridge-soma#16]
```
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-soma@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build'
npm ERR!   SOLINK_MODULE(target) Release/obj.target/noble.node
npm ERR! make: Leaving directory '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/homebridge/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/homebridge/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/homebridge/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [noble.target.mk:20: Release/obj.target/noble.node] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.10.90-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-01-24T13_00_36_982Z-debug-0.log

Command failed. Please review log for details.
```
nodejs -v16.13.2
node -v16.13.2
npm -v8.3.2

any ideas @ebaauw ?

**Comment by ebaauw** [comment]
Raspbian Stretch?

**Comment by costispavlou** [comment]
![image](https://user-images.githubusercontent.com/57916603/150794363-1c1b773d-7150-4a2e-a624-05c74111125d.png)

**Comment by costispavlou** [comment]
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by ebaauw** [comment]
Is the the lite or full version?

Did you previously install Homebridge SOMA on this machine?  What has changed since, did you upgrade the OS?  If no changes to the OS, I would check the file system on the uSD card and the card itself.

**Comment by costispavlou** [comment]
I upgraded the os yes. 
Same Homebridge though everything is fine, it's just the upgrade that goes bad.

Do I need to reinstall soma?

**Comment by costispavlou** [comment]
I removed soma and reinstalled
this happened: 
`USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-soma@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build'
npm ERR!   SOLINK_MODULE(target) Release/obj.target/noble.node
npm ERR! make: Leaving directory '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | arm
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/homebridge/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/homebridge/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/homebridge/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: g++: No such file or directory
npm ERR! make: *** [noble.target.mk:20: Release/obj.target/noble.node] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.10.90-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-soma/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-01-24T13_53_48_909Z-debug-0.log

Command failed. Please review log for details.`

**Comment by costispavlou** [comment]
Am I right to think its an issue with npm ?

**Comment by ebaauw** [comment]
The issue is that you have no C-compiler.  Could be missing from the lite version of the OS, in which case you need to install it manually through `apt`.  Not sure what package(s) it is.  Could also be a file system corruption.

**Comment by ebaauw** [comment]
For the install, see https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#step-1-install-nodejs

**Comment by costispavlou** [comment]
how is my OS lite ?

**Comment by ebaauw** [comment]
Because you chose the lite version when writing the image to the uSD card.

**Comment by costispavlou** [comment]
How can you know that my OS is the lite version? I don't understand. 
Bullseye supposedly is the latest version.. 
In any case, can I upgrade to full OS ? 
and why this plugin was working before the OS upgrade? 
I'm asking because everything else (qbt, radarr, sonarr, links, conky, etc etc) works fine

**Comment by ebaauw** [comment]
The full version includes the C-compiler for sure.  I don’t know for sure about the lite version, but that could explain why you have no C-compiler.

**Comment by costispavlou** [comment]
My OS is the full version I don't get why/how you concluded to that.
gcc is already the newest version (4:10.2.1-1+rpi1).

**Comment by ebaauw** [comment]
I don’t conclude anything.  `npm` reports that `g++` is missing.  Either it hasn’t been installed, or it’s been lost due to corruption.  I’m only trying to help you figure out which.

**Comment by costispavlou** [comment]
I know you are and thank you. 
I'm just trying to find out what's wrong as well. 
Do you know the command to install g++ ?

**Comment by costispavlou** [comment]
sudo apt install -y nodejs gcc g++ make python net-tools

did the trick.
