### ISSUE TITLE
Does nothing if not running directly on a Pi

### ISSUE THREAD

**Issue by washcroft** [ebaauw/homebridge-soma#2]
Hello,
Firstly, thanks for creating this - finally a decent Homebridge plugin for Soma products without having to use the separate SomaConnect homebridge!

I run Homebridge in a Docker container on a Pi, so although it is Linux on arm, this line prevents things from working:

https://github.com/ebaauw/homebridge-soma/blob/ba127028fbdb0ab490bfda0c2e4035b6dc163e27/lib/BleClient.js#L244

...since the file does not exist, but you're trying to stat it. Simply change to a file exists check, so that if it doesn't, the "unsupported platform" warning is still given, but at least the plugin/CLI tools can be used by those a little more adventurous ;)

I'm getting a few other niggles logged, but I'll report those separately if needed once I've had chance to play/test more.

e.g.

```
RangeError: hardwareRevision: unknown characteristic key

RangeError: softwareRevision: unknown characteristic key

TypeError: Cannot read property 'shadeService' of undefined

[9/7/2021, 3:07:19 PM] [SOMA] Alfie's B/Room Trigger 1: set Enabled to true
[9/7/2021, 3:07:19 PM] [SOMA] Alfie's B/Room Trigger 1: set Resource to "Every Day at :00"
[9/7/2021, 3:07:20 PM] [SOMA] Alfie's B/Room Trigger 2: set Enabled to true
[9/7/2021, 3:07:20 PM] [SOMA] Alfie's B/Room Trigger 2: set Resource to "Every Day at :00"

```

**Comment by ebaauw** [comment]
Is the `stat()` throwing on a non-existent file?  That’s definitely not what I intended.  Is is meant as a hack to detect a Raspberry Pi, since there’s many other arm systems running linux.

As for the `RangeError` and `TypeError` messages: They’re issued when Noble doesn’t create the Service or Characteristic on discovery, or when it doesn’t create the Peripheral on connect.  I haven’t been able to reproduce when this happens.

> [9/7/2021, 3:07:19 PM] [SOMA] Alfie's B/Room Trigger 1: set Resource to "Every Day at :00"

This is the on-device trigger, but apparently it isn’t parsed correctly.  What does the SOMA Smart Shades app show?  Do you have a gen-1 device?  What firmware does it run?  Could you please capture and attach the output of `soma -DDD probe "Alfie's B/Room"`.  That should log all the raw binary data the device reports.  It might take a few attempts to succeed, if the BLE connection is poor, or if Noble feels like acting out.

**Comment by washcroft** [comment]
I imagine it's silently throwing an error (hidden by async?) either way it doesn't work, can't even do a discover in the cli without that file existing.

The triggers are set for open at 08:30 and closing at 18:30.

I have a mix of gen 1/2 devices, I will send some dumps shortly.

**Comment by ebaauw** [comment]
> I imagine it's silently throwing an error (possibly hidden by async?)

No the scanning for devices simply isn't started, because of the error thrown by `fa.stat()`.

Could you please try v0.0.13?

**Comment by ebaauw** [comment]
> [9/7/2021, 3:07:19 PM] [SOMA] Alfie's B/Room Trigger 1: set Resource to "Every Day at :00"

Damn, that's another bug.  I had tested this, but apparently I changed the date/time logic after that.  The devices do local time instead of UTC and I somehow managed to mess up the conversions.

**Comment by washcroft** [comment]
> Could you please try v0.0.13?

Thanks, I can confirm the vcgencmd issue is now fixed. It looks like you have committed a fix for the trigger hour log message too.

In case you need them to help with anything else, here are some dumps:

[Alfie's B/Room - Gen 2 f/w 2.2.7](https://github.com/ebaauw/homebridge-soma/files/7126508/Alfie.txt)

[Alfie's B/Room - Gen 2 f/w upgraded to 2.2.9](https://github.com/ebaauw/homebridge-soma/files/7126544/Alfie229.txt)

[Daisy's B/Room -  Gen 1 f/w 2.2.4](https://github.com/ebaauw/homebridge-soma/files/7126509/Daisy.txt)

[Kitchen -  Gen 1 f/w 2.2.9](https://github.com/ebaauw/homebridge-soma/files/7126534/Kitchen.txt)

**Comment by ebaauw** [comment]
The Smart Shades 2 is almost indistinguishable from the Tilt 2 (which I have), except for the `venetianMode` setting in the `motorCalibration` settings and the corresponding bit in the advertisement.  Gen 2 and gen 1 devices run the same firmware, but have a different hardware version (staring with `BLINDY_V9` vs `BLINDY_V8`).  I'll change the _Model Identifier_ based on that.

> What's "motorTouchButton", do these units have some hidden touch points that aren't enabled? 

I understand that the gen-1 devices have a physical button, not sure what it does.  The gen-2 devices expose this characteristic (makes sense: same firmware), but it doesn't do anything.  I'll see if I can expose _Lock Physical Controls_ on the gen-1 devices, so you can change this from HomeKit.

I also understand that the gen-1 devices were able to play different sounds, but I'm not sure if they still have that capability with the current firmware.

**Comment by washcroft** [comment]
> I understand that the gen-1 devices have a physical button, not sure what it does.

> I also understand that the gen-1 devices were able to play different sounds, but I'm not sure if they still have that capability with the current firmware.

I'm not aware of any physical button on the Gen 1 units (unless it's a capacitive touch button hidden somewhere), and as far as I can remember there has never been an option to enable/use it in the latest or early firmware/app versions. Same goes for sounds, I don't remember seeing anything to control sounds in the early firmware/app versions.
