### ISSUE TITLE
error: connection canceled!

### ISSUE THREAD

**Issue by niqbert** [ebaauw/homebridge-soma#21]
Hello,

I had to reinstall my homebridge and after all, I get following error:

[21/05/2022, 13:25:48] [SOMA] Rollo Wohnz: warning: connection canceled!
[21/05/2022, 13:25:48] [SOMA] Rollo Wohnz: warning: connection canceled!
[21/05/2022, 13:25:48] [SOMA] Rollo Wohnz: error: connection canceled!
[21/05/2022, 13:25:48] [SOMA] Rollo Wohnz: error: connection canceled!

A re-install of the plugin did not help. What can I do?

**Comment by ebaauw** [comment]
This is an error returned by Noble to Homebridge SOMA, that the BLE connection to the SOMA device has been lost.  Could be a radio issue, could be an issue with the Bluetooth stack on the Homebridge server.  Make sure you don’t use any other clients to connect to the SOMA device (incl. the SOMA app or connect), that the BLE antenna of the server has a direct line of sight to the SOMA device and isn’t too far away.  And make sure you run Homebridge SOMA on a Raspberry Pi with 32-bit Raspberry Pi OS.

**Comment by niqbert** [comment]
After a third re-install the devices worked. But when I restart the server, I get the error, that bluetooth is deactivated. Then I do "sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)" and restart Homebridge. After that I get again the error connection canceled.

**Comment by niqbert** [comment]
I did the third reset of the microSD card with the today released HomebridgeOS. After the backup it seems fine, again. Hope it will be fine the next days, weeks and months :)
