### ISSUE TITLE
home bridge indicates disconnected unexpectedly

### ISSUE THREAD

**Issue by afleonc** [ebaauw/homebridge-soma#23]
Hello, I know this project is no longer being maintained but maybe you can guide me on the cause of this failure my system is:
Node.js Version: v16.17.0
[SOMA] hardware: Raspberry Pi 4B 1.4 (8GB)
[SOMA] os: Debian GNU/Linux 11 (bullseye)
[SOMA] restored 1 accessories from cache
[SOMA] warning: This plugin is no longer being maintained, see README.
[SOMA] warning: unsupported platform
[SOMA] bluetooth [E4:5F:01:2E:B4:DA] enabled

every time I try to control the shades via HomeKit I get the following error:
**Cortinas: warning: request 57: disconnected unexpectedly**

Here is a screenshot

![image](https://user-images.githubusercontent.com/4024665/193392678-424b5163-f9d7-4ec8-8ac1-7ea7b53ea067.png)

The shade status gets updated to the actual state of the shades but every time I request the motorService to move the shades I get the response above and the shades do not move, hopefully you can help me out

**Comment by ebaauw** [comment]
The position and battery are updated from the BLE advertisements sent by the shades.  For the remaining state, and to control the shades, a BLE connection from Homebridge SOMA to the shade is needed.  As mentioned in the README, I haven’t been able to get a BLE connection from NodeJS stable enough for my standards, and I stopped trying.  You might check some of the closed issues for tips, like #19, #20, #21, but between the unsupported OS and firmware version of the shade you’re running, I’m afraid these might not solve your issue.

**Comment by afleonc** [comment]
Thanks for your quick response I’ll check the options
