### ISSUE TITLE
Light Sensor iOS 15.1

### ISSUE THREAD

**Issue by niqbert89** [ebaauw/homebridge-soma#5]
I was happy to hear that with iOS 15.1 we can create automations when somehting is lower or higher then adjusted. Now i created an automation „when light sensor is under lux then open the shade“. But I cant adjust the shade, because for iOS I already used the shade for the light sensor. 

Is it possible to make the light sensor as an extra device?

**Comment by ebaauw** [comment]
I though I had answered this issue, but apparently my commentt wasn't saved.  Sorry for the delay.

> when light sensor is under lux then open the shade

This kind of automations are best done on the device, using the Smart Shades app by SOMA.  When creating a trigger, you can select the light level as condition under _When_, provided the solar panel is connected, and detecting light.

These kind of automations have been possible in HomeKit for a long time, using a decent HomeKit app.  The iOS 15.1 change is for the Home app, not for HomeKit.  You might need to create a HomeKit scene to set the shade position; that would be needed if you use another HomeKit app anyway (Home just creates a hidden scene under the hood).

> Is it possible to make the light sensor as an extra device?

Technically, yes, but I won't.  In fact, earlier versions of Homebridge SOMA (before 0.0.14) did so.  However, it didn't work out well, see #3.
